### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by masterbaty1** [hyperfield/ai-file-sorter#26]
I've been trying for several days to get this to load on Windows 11. Followed the instructions without any change except the version of cuda I changed to 13.0 . When I finally got it to install with cuda I keep getting a missing dll file error, i've tried uninstalling and reinstalling without cuda and get the same message.

<img width="1164" height="887" alt="Image" src="https://github.com/user-attachments/assets/3267593f-4c71-4179-a6d8-fd99ea2e75a9" />

Any  guidance would be much appreciated .

Thank you

**Comment by hyperfield** [comment]
> Furthermore, the standalone version is blocked by our virus scanner.

I've just checked the files on [VirusTotal](https://www.virustotal.com/), which scans with 70+ antivirus engines, and nothing was detected.

**Comment by hyperfield** [comment]
This issue should be fixed in the latest version, which also has some additional features and improvements. Please [try it ](https://sourceforge.net/projects/ai-file-sorter/).

**Comment by transfererror** [comment]
It still doesn't work with version 0.97. I think the problem is linked to problems with llama.cpp.
When running
`powershell -ExecutionPolicy Bypass -File .\build_llama_windows.ps1 cuda=on`
I get several errors starting with

<img width="945" height="727" alt="Image" src="https://github.com/user-attachments/assets/b8233f47-40e2-41f6-a15d-a29d0e9927ab" />
The installer and the stand-alone-version do not run either.

**Comment by transfererror** [comment]
I finally was able to compile everything without error. But also this didn't help: Neither the compiled nor the installer- nor the stand-alone version can be started. In the taskmanager the exe appears, but after a couple of seconds it disappears again. Too bad.
